# Generated by Django 4.0.5 on 2022-07-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='main_patient_single_instance'),
        ),
    ]
