# Generated by Django 4.0.5 on 2022-07-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_patient_main_patient_single_instance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='main_patient_single_instance',
        ),
    ]
