# Generated by Django 4.0.5 on 2022-07-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_patient_main_patient_single_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='single_patient',
        ),
    ]
