# Generated by Django 4.0.5 on 2022-07-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_chat_users_chat_first_user_chat_second_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
